// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgDeckApi.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MtgDeckApi.Migrations
{
    [DbContext(typeof(MtgDeckApiContext))]
    [Migration("20200505192427_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MtgDeckApi.Models.CardModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CardDescription")
                        .HasColumnType("text");

                    b.Property<string>("CardImg")
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .HasColumnType("text");

                    b.Property<long?>("DeckModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ManaCost")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeckModelId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MtgDeckApi.Models.DeckModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DeckName")
                        .HasColumnType("text");

                    b.Property<long?>("UserModelId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("MtgDeckApi.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MtgDeckApi.Models.CardModel", b =>
                {
                    b.HasOne("MtgDeckApi.Models.DeckModel", null)
                        .WithMany("CardsInDeck")
                        .HasForeignKey("DeckModelId");
                });

            modelBuilder.Entity("MtgDeckApi.Models.DeckModel", b =>
                {
                    b.HasOne("MtgDeckApi.Models.UserModel", null)
                        .WithMany("UserDecks")
                        .HasForeignKey("UserModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
